import type { Metadata } from "next";
import { Poppins, Noto_Sans } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
  
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-sans",        // <- default app font
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  weight: ["100", "900"],
  variable: "--font-noto",        // <- optional secondary font
});

export const metadata: Metadata = {
  title: "Create React App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      // expose CSS vars; Tailwind will point font-sans to --font-sans
      className={`${poppins.variable} ${notoSans.variable}`}
    >
      <head>
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
